version: "3.9"
services:
  python1:
    image: python:latest
    container_name: python1
    ports:
    - "8080:8080"
    command: ["bin/bash"]
    volumes:
    - ./:/code
    stdin_open: true
    tty: true
  python2:
    image: python:latest
    container_name: python2
    ports:
    - "8081:8080"
    command: ["bin/bash"]
    volumes:
    - ./:/code
    stdin_open: true
    tty: true
  python3:
      image: python:latest
      container_name: python3
      ports:
        - "8082:8080"
      command: [ "bin/bash" ]
      volumes:
        - ./:/code
      stdin_open: true
      tty: true



    